Revert "use tokio_reactor::Handle::default"
The reverted commit introduced the following problem on Windows:

  Starting sccache server...
  error: Timed out waiting for server startup

This reverts commit b43d51fa2e536019c113cc79cd98dcc2861afad4.